---
  - name: Ensure couchpotato dependencies are installed
    apt: name={{ item }} state=present
    with_items: packages
    when: ansible_os_family == "Debian"

  - name: Ensure couchpotato dependencies are installed
    yum: name={{ item }} state=present
    with_items: packages
    when: ansible_os_family == "RedHat"

  - name: Fetch couchpotato from GitHub
    git: repo=git://github.com/RuudBurger/CouchPotatoServer
         dest={{ couchpotato_base }}/couchpotato
         update=no
         accept_hostkey=True

  - name: Deploy couchpotato service script
    command: cp {{ couchpotato_base }}/couchpotato/init/couchpotato.fedora.service /etc/systemd/system/couchpotato.service
    notify: restart couchpotato
    when: system_init == "systemd"

  - name: Deploy CouchPotato service script
    command: cp {{ couchpotato_base }}/couchpotato/init/ubuntu /etc/init.d/couchpotato
    notify: restart couchpotato
    when: system_init == "upstart"

  - name: Create couchpotato user
    user: >
        name={{ couchpotato_user_name }}
        comment="Couchptato user"

  - name: Start couchpotato and enabled start at boot
    service: name=couchpotato state=started enabled=yes

  - name: Set ownership to couchpotato user
    file: path={{ item.path }} owner={{ couchpotato_user_name }}
    with_items:
      - { path: "{{ couchpotato_base }}/couchpotato" }

  - name: Set Additional ownership
    file: path={{ item.path }} owner={{ couchpotato_user_name }}
    with_items:
      - { path: "/var/opt/couchpotato" }
    when: ansible_os_family == "Debian"
