---
  - name: Ensure CouchPotato dependencies are installed
    apt: name={{ item }} state=present
    with_items: packages
    when: ansible_os_family == "Debian"

  - name: Ensure CouchPotato dependencies are installed
    apt: name={{ item }} state=present
    with_items: packages
    when: ansible_os_family == "RedHat"

  - name: Fetch CouchPotato from GitHub
    git: repo=git://github.com/RuudBurger/CouchPotatoServer
         dest={{ couchpotato_base }}/couchpotato
         update=no
         accept_hostkey=True

  - name: Deploy CouchPotato service script
    copy: dest=/etc/systemd/system/couchpotato.service
              src={{ couchpotato_base }}/couchpotato/init/couchpotato.fedora.service
              owner=root group=root mode=755
    notify: restart couchpotato
    when: system_init == "systemd"

  - name: Deploy CouchPotato service script
    command: cp {{ couchpotato_base }}/couchpotato/init/ubuntu /etc/init.d/couchpotato
    notify: restart couchpotato
    when: system_init == "upstart"

  - name: Create couchpotato user
    user: >
        name={{ couchpotato_user_name }}
        comment="Couchptato user"

  - name: Ensure the CouchPotato service is running and enabled on boot
    service: name=couchpotato state=started enabled=yes

  - name: Set ownership
    file: path={{ item.path }} owner={{ couchpotato_user_name }}
    with_items:
      - { path: "{{ couchpotato_base }}/couchpotato" }
      - { path: "/var/opt/couchpotato" }
